### ISSUE TITLE
TwoFactorAuthenticationService throws an exception for Doctrine\Persistence\ObjectManager

### ISSUE THREAD

**Issue by wuestenmagier** [yeebase/Yeebase.TwoFactorAuthentication#3]
After updating Neos an error has occured. With doctrine/persistence 1.2.0 everything ist working well. But after updating there seems to be a problem with doctrine/persistence 1.3.3. Is there a fix coming?

**Exception**

`Exception #1265213849 in line 359 of /data/Packages/Framework/Neos.Flow/Classes/ObjectManagement/DependencyInjection/ProxyClassBuilder.php: The object "Doctrine\Persistence\ObjectManager" which was specified as a property in the object configuration of object "Yeebase\TwoFactorAuthentication\Service\TwoFactorAuthenticationService" (automatically registered class) does not exist. Check for spelling mistakes and if that dependency is correctly configured.`

**Comment by bwaidelich** [comment]
Apparently Doctrine introduced a breaking change in a minor version update :-/
We could fix it by referring to the `EntityManagerInterface` instead of the `ObjectManager`

**Comment by bwaidelich** [comment]
@wuestenmagier I couldn't test it but could you check whether #4 solves the issue for you?

**Comment by albe** [comment]
Referencing https://github.com/doctrine/persistence/pull/71 for visibility of this breakiness

**Comment by wuestenmagier** [comment]
Yes, this is working. Checked some pages if the exception is still thrown. The login also works well.

**Comment by bwaidelich** [comment]
Thanks for reporting & checking, a new version was released: https://packagist.org/packages/yeebase/twofactorauthentication#2.1.1
